name: it-tools
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - proxy
    environment:
      - TZ=Asia/Bangkok

networks:
  proxy:
    external: true
